set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

# --- MACHINE IDENTIFIERS
set(TARGET_TRIPLE "riscv64-none-none-eabi")
set(TARGET_ARCH "rv64gc")
set(TARGET_ABI "lp64")

# --- TOOLS
set(CMAKE_C_COMPILER clang)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_Swift_COMPILER swiftc)
set(CMAKE_LINKER ld.lld)

# --- INITIAL COMPILER FLAGS
set(CMAKE_C_FLAGS_INIT "-target ${TARGET_TRIPLE} -march=${TARGET_ARCH} -mabi=${TARGET_ABI} -DRISCV64")
set(CMAKE_ASM_FLAGS_INIT "-target ${TARGET_TRIPLE} -march=${TARGET_ARCH} -mabi=${TARGET_ABI}")
set(CMAKE_Swift_FLAGS_INIT "-target ${TARGET_TRIPLE} -Xcc -march=${TARGET_ARCH} -Xcc -mabi=${TARGET_ABI} -Xcc -DRISCV64")

# --- SANITY CHECKS
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_ASM_COMPILER_WORKS TRUE)
set(CMAKE_ASM_COMPILER_FORCED TRUE)
set(CMAKE_Swift_COMPILER_WORKS TRUE)
set(CMAKE_Swift_COMPILER_FORCED TRUE)
